package com.sunil.greendaorxapp.daogen;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.

/**
 * Entity mapped to table "NOTE".
 */
@Entity
public class Note {

    @Id
    private Long id;

    @NotNull
    private String tittle;
    private String comment;
    private String noteDate;

    @Generated(hash = 1272611929)
    public Note() {
    }

    public Note(Long id) {
        this.id = id;
    }

    @Generated(hash = 656071469)
    public Note(Long id, @NotNull String tittle, String comment, String noteDate) {
        this.id = id;
        this.tittle = tittle;
        this.comment = comment;
        this.noteDate = noteDate;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    @NotNull
    public String getTittle() {
        return tittle;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setTittle(@NotNull String tittle) {
        this.tittle = tittle;
    }

    public String getComment() {
        return comment;
    }

    public void setComment(String comment) {
        this.comment = comment;
    }

    public String getNoteDate() {
        return noteDate;
    }

    public void setNoteDate(String noteDate) {
        this.noteDate = noteDate;
    }

}
